### ISSUE TITLE
Include CERN shuttle timetable

### ISSUE THREAD

**Issue by AdrianAlan** [AdrianAlan/cern-maps#15]
@AndreaGiardini I'm gonna need a json for this

**Comment by AndreaGiardini** [comment]
Is http://tmp-pub.ifndef.it/cernMaps/ enough?

**Comment by AdrianAlan** [comment]
Can we have something like this on the serv? 
https://github.com/AdrianAlan/cern-maps/blob/master/assets/shuttle.json

**Comment by AndreaGiardini** [comment]
Done

**Comment by AdrianAlan** [comment]
Great
