### ISSUE TITLE
Implement TPG API

### ISSUE THREAD

**Issue by AndreaGiardini** [AdrianAlan/cern-maps#8]
TPG released a nice API service to get the bus timetables

http://www.tpg.ch/web/open-data/donnees

Cool to implement!

**Comment by AdrianAlan** [comment]
This form still doesn't work! I've just sent them an email, we'll see...

**Comment by AndreaGiardini** [comment]
#noteforthefutureme

In the API conditions it's specified that we should mention TPG in the applicaion since all the datas are obtained through their wonderful service.

**Comment by AdrianAlan** [comment]
OK, I got it :)

**Comment by AdrianAlan** [comment]
@AndreaGiardini 
The JSON has some useless fields. I'd prefer simple as current one here https://github.com/AdrianAlan/cern-maps/blob/master/assets/trams.json
With a difference that it would be best to get timetable for each stop of Y and 18. Best could be something like this:
"tgp": [
--line: String
--direction: String
--stop: String
--times: Array
]
I like the idea to distribute this to many small jsons, will be faster (perhaps <line>-<direction>.json is enough :)

Tell me when I can proceed

**Comment by AdrianAlan** [comment]
@AndreaGiardini  Do you think we should include 14? Summer returns may be late :P

**Comment by AdrianAlan** [comment]
NA is cool as well

**Comment by AndreaGiardini** [comment]
Mh... Your last comment made me think...
Do we want also trams *to* CERN and not only *from* CERN?

**Comment by AdrianAlan** [comment]
I'd want this. But open question
